GET http://localhost:8080/camunda/process-definitions

###

POST http://localhost:8080/camunda/process/my-project-process:1:b37c57a6-c0dd-11ee-8076-64c901ae1890/start
accept: */*
Content-Type: application/json

{
  "alertJson": "string"
}

###
GET http://localhost:8080/camunda/tasks/active
accept: */*
Content-Type: application/json

{
  "alertJson": "string"
}

###



###
POST http://localhost:8080/engine-rest/process-definition/key/flow/start
Authorization: Basic demo demo
Accept: application/json
Content-Type: application/json

{
  "variables": {
    "creditor": {"value":"Niall","type":"String"},
    "amount":{"value":"100.1","type":"Double"},
    "counter":{"value":"100","type":"Integer"},
    "invoiceNumber":{"value":"123","type":"String"},
    "broker": {
      "value": "{\"name\":\"Broker Name\"}",
      "type": "json"
    }
  }
}

###

